const TRADE_MEASUREMENT_REGISTRY = {
  sitework: {
    scopeKey: 'sitework',
    preferredPrimaryUnits: ['sqft', 'cy', 'lf'],
    allowedPricingUnits: ['sqft', 'cy', 'lf', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  excavation: {
    scopeKey: 'excavation',
    preferredPrimaryUnits: ['cy'],
    allowedPricingUnits: ['cy', 'ls'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: false,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  foundation: {
    scopeKey: 'foundation',
    preferredPrimaryUnits: ['floor_sqft', 'lf', 'cy', 'sqft'],
    allowedPricingUnits: ['floor_sqft', 'lf', 'cy', 'sqft', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_structural_takeoff',
  },
  framing: {
    scopeKey: 'framing',
    preferredPrimaryUnits: ['package', 'ls', 'unknown'],
    allowedPricingUnits: ['living_sqft', 'ls', 'package'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  roofing: {
    scopeKey: 'roofing',
    preferredPrimaryUnits: ['roof_square', 'roof_sqft', 'sqft'],
    allowedPricingUnits: ['roof_square', 'roof_sqft', 'sqft', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  exterior: {
    scopeKey: 'exterior',
    preferredPrimaryUnits: ['surface_sqft', 'sqft'],
    allowedPricingUnits: ['surface_sqft', 'sqft', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  mep_rough: {
    scopeKey: 'mep_rough',
    preferredPrimaryUnits: ['ea', 'fixture', 'ls'],
    allowedPricingUnits: ['living_sqft', 'ls', 'ea', 'fixture'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_count',
  },
  insulation: {
    scopeKey: 'insulation',
    preferredPrimaryUnits: ['surface_sqft', 'sqft'],
    allowedPricingUnits: ['surface_sqft', 'sqft', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  drywall: {
    scopeKey: 'drywall',
    preferredPrimaryUnits: ['surface_sqft', 'sqft'],
    allowedPricingUnits: ['surface_sqft', 'sqft', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  paint_trim: {
    scopeKey: 'paint_trim',
    preferredPrimaryUnits: ['surface_sqft', 'lf', 'sqft'],
    allowedPricingUnits: ['surface_sqft', 'lf', 'sqft', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  cabinets_counters: {
    scopeKey: 'cabinets_counters',
    preferredPrimaryUnits: ['lf', 'ea', 'ls'],
    allowedPricingUnits: ['lf', 'ea', 'ls', 'sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: false,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_allowance',
  },
  tile_flooring: {
    scopeKey: 'tile_flooring',
    preferredPrimaryUnits: ['floor_sqft', 'sqft'],
    allowedPricingUnits: ['floor_sqft', 'sqft', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_takeoff',
  },
  appliances: {
    scopeKey: 'appliances',
    preferredPrimaryUnits: ['ea'],
    allowedPricingUnits: ['ea', 'ls'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: false,
    canUseLivingSfAsBenchmark: false,
    missingQuantityBehavior: 'needs_count',
  },
  hvac: {
    scopeKey: 'hvac',
    preferredPrimaryUnits: ['ton', 'ea', 'ls'],
    allowedPricingUnits: ['ton', 'ea', 'ls', 'living_sqft'],
    allowedBenchmarkUnits: ['living_sqft'],
    canUseLivingSfAsPrimary: false,
    canUseLivingSfAsPricing: true,
    canUseLivingSfAsBenchmark: true,
    missingQuantityBehavior: 'needs_count',
  },
};

const NO_LIVING_SF_PRIMARY_SEED_KEYS = new Set(Object.keys(TRADE_MEASUREMENT_REGISTRY));

function getTradeMeasurementProfile(scopeKey) {
  return TRADE_MEASUREMENT_REGISTRY[scopeKey] || null;
}

function missingStatusForScope(scopeKey) {
  return getTradeMeasurementProfile(scopeKey)?.missingQuantityBehavior || 'needs_takeoff';
}

module.exports = {
  TRADE_MEASUREMENT_REGISTRY,
  NO_LIVING_SF_PRIMARY_SEED_KEYS,
  getTradeMeasurementProfile,
  missingStatusForScope,
};
