/**
 * Backend mirror of subcontractor trade keys and scope allowlists.
 * Stucco backend allowlist intentionally unchanged from pre-Phase-0 behavior.
 */
const PLAN_EXPORT_TRADE_KEYS = [
  'electrical',
  'plumbing',
  'hvac',
  'roofing',
  'concrete',
  'framing',
  'drywall',
  'stucco',
  'insulation',
  'flooring',
  'windows_doors',
];

const TRADE_SCOPE_ALLOWLISTS = {
  electrical: ['electrical_rough'],
  stucco: ['stucco'],
  roofing: [
    'roofing_system',
    'tear_off',
    'decking_repair',
    'underlayment',
    'ice_water_shield',
    'shingles_roofing',
    'drip_edge',
    'ridge_cap',
    'valley_flashing',
    'step_flashing',
    'wall_flashing',
    'ridge_vent',
    'roof_vents',
    'turbine_vents',
    'pipe_boots',
    'chimney_flashing',
    'skylight_flashing',
    'roof_penetrations',
    'flashing',
    'vents_penetrations',
    'roof_repairs',
    'roof_pitch_complexity_access',
    'roof_exclusions',
    'gutters',
    'downspouts',
    'permits',
    'cleanup',
  ],
  hvac: [
    'service_call',
    'equipment_replace',
    'refrigerant',
    'thermostat',
    'ductwork',
    'ventilation',
    'permits',
    'cleanup',
  ],
  concrete: [
    'demo_removal',
    'site_prep',
    'excavation',
    'reinforcement',
    'complex_forming',
    'pour_flatwork',
    'pour_foundation',
    'concrete_sealer',
    'decorative_finish',
    'additional_haul_off',
  ],
  framing: [
    'layout',
    'wall_framing',
    'openings',
    'blocking',
    'shear_sheathing',
    'hardware',
    'materials_package',
    'labor',
    'cleanup',
  ],
  drywall: [
    'demo_removal',
    'hang',
    'finish_tape',
    'texture',
    'patch_repair',
    'cleanup',
  ],
  plumbing: [
    'service_call',
    'fixture_repair',
    'fixture_replace',
    'drain_cleaning',
    'water_line',
    'sewer_line',
    'plumbing_rough',
    'plumbing_trim',
    'parts_materials',
    'emergency_fee',
    'cleanup',
  ],
  insulation: ['insulation'],
  flooring: [
    'floor_demo',
    'floor_prep',
    'flooring',
    'flooring_lvp',
    'flooring_laminate',
    'flooring_engineered_hardwood',
    'flooring_solid_hardwood',
    'tile_flooring',
    'flooring_carpet',
    'underlayment',
    'moisture_barrier',
    'transitions',
    'quarter_round',
    'trim',
    'adhesive_mastic_removal',
    'cleanup',
  ],
  windows_doors: [
    'windows',
    'exterior_doors',
    'sliding_doors',
    'garage_doors',
    'windows_doors',
  ],
};

function getTradeScopeAllowlist(tradeKey) {
  if (!tradeKey) return null;
  const allowlist = TRADE_SCOPE_ALLOWLISTS[tradeKey];
  return allowlist?.length ? allowlist : null;
}

module.exports = {
  PLAN_EXPORT_TRADE_KEYS,
  TRADE_SCOPE_ALLOWLISTS,
  getTradeScopeAllowlist,
};
