/**
 * Backend mirror of subcontractor trade keys and scope allowlists.
 * Stucco backend allowlist intentionally unchanged from pre-Phase-0 behavior.
 */
const PLAN_EXPORT_TRADE_KEYS = [
  "electrical",
  "plumbing",
  "hvac",
  "roofing",
  "concrete",
  "framing",
  "drywall",
  "stucco",
  "insulation",
  "flooring",
  "painting",
  "windows_doors",
  "garage_doors",
];

const TRADE_SCOPE_ALLOWLISTS = {
  electrical: [
    "electrical_rough",
    "electrical_trim",
    "electrical",
    "electrical_main_panel",
    "electrical_subpanel",
    "electrical_panel_upgrade",
    "electrical_service_upgrade",
    "electrical_standard_circuit",
    "electrical_dedicated_20a",
    "electrical_circuit_30a",
    "electrical_circuit_40a",
    "electrical_circuit_50a",
    "electrical_circuit_60a_plus",
    "electrical_standard_receptacle",
    "electrical_gfci_receptacle",
    "electrical_afci_receptacle",
    "electrical_exterior_receptacle",
    "electrical_floor_receptacle",
    "electrical_usb_receptacle",
    "electrical_240v_receptacle",
    "electrical_single_pole_switch",
    "electrical_3way_switch",
    "electrical_4way_switch",
    "electrical_dimmer_switch",
    "electrical_occupancy_switch",
    "electrical_smart_switch",
    "electrical_standard_fixture",
    "electrical_recessed_light",
    "electrical_pendant_light",
    "electrical_decorative_light",
    "electrical_exterior_light",
    "electrical_undercabinet_light",
    "electrical_ceiling_fan",
    "electrical_bath_exhaust_fan",
    "electrical_range_hookup",
    "electrical_dryer_hookup",
    "electrical_dishwasher_hookup",
    "electrical_disposal_hookup",
    "electrical_microwave_hookup",
    "electrical_refrigerator_hookup",
    "electrical_water_heater_hookup",
    "electrical_hvac_hookup",
    "electrical_ev_charger_hookup",
    "electrical_smoke_detector",
    "electrical_co_detector",
    "electrical_doorbell",
    "electrical_cat6_drop",
    "electrical_tv_coax",
    "electrical_security_prewire",
    "electrical_camera_prewire",
    "electrical_device_removal",
    "electrical_fixture_removal",
    "electrical_relocate",
    "electrical_abandoned_circuit",
    "electrical_conduit",
    "electrical_trenching",
    "cleanup",
  ],
  stucco: ["stucco"],
  roofing: [
    "roofing_system",
    "tear_off",
    "decking_repair",
    "underlayment",
    "ice_water_shield",
    "shingles_roofing",
    "drip_edge",
    "ridge_cap",
    "valley_flashing",
    "step_flashing",
    "wall_flashing",
    "ridge_vent",
    "roof_vents",
    "turbine_vents",
    "pipe_boots",
    "chimney_flashing",
    "skylight_flashing",
    "roof_penetrations",
    "flashing",
    "vents_penetrations",
    "roof_repairs",
    "roof_pitch_complexity_access",
    "roof_exclusions",
    "gutters",
    "downspouts",
    "permits",
    "cleanup",
  ],
  hvac: [
    "hvac",
    "service_call",
    "equipment_replace",
    "refrigerant",
    "thermostat",
    "ductwork",
    "ventilation",
    "permits",
    "cleanup",
  ],
  concrete: [
    "demo_removal",
    "site_prep",
    "excavation",
    "reinforcement",
    "complex_forming",
    "pour_flatwork",
    "pour_foundation",
    "concrete_sealer",
    "decorative_finish",
    "additional_haul_off",
  ],
  framing: [
    "layout",
    "wall_framing",
    "openings",
    "blocking",
    "shear_sheathing",
    "hardware",
    "materials_package",
    "labor",
    "cleanup",
  ],
  drywall: [
    "drywall",
    "demo_removal",
    "hang",
    "finish_tape",
    "texture",
    "patch_repair",
    "cleanup",
  ],
  plumbing: [
    "service_call",
    "fixture_repair",
    "fixture_replace",
    "drain_cleaning",
    "water_line",
    "sewer_line",
    "plumbing_rough",
    "plumbing_trim",
    "parts_materials",
    "emergency_fee",
    "cleanup",
  ],
  insulation: ["insulation", "cleanup"],
  flooring: [
    "floor_demo",
    "floor_prep",
    "flooring",
    "flooring_lvp",
    "flooring_laminate",
    "flooring_engineered_hardwood",
    "flooring_solid_hardwood",
    "tile_flooring",
    "flooring_carpet",
    "underlayment",
    "moisture_barrier",
    "transitions",
    "quarter_round",
    "trim",
    "adhesive_mastic_removal",
    "cleanup",
  ],
  painting: [
    "prep",
    "interior_paint",
    "ceiling_paint",
    "trim_paint",
    "door_paint",
    "cabinet_paint",
    "exterior_prep",
    "exterior_paint",
    "cleanup",
  ],
  windows_doors: [
    "windows",
    "exterior_doors",
    "sliding_doors",
    "interior_doors",
    "windows_doors",
  ],
  garage_doors: ["garage_doors", "garage_door_openers"],
};

function getTradeScopeAllowlist(tradeKey) {
  if (!tradeKey) return null;
  const allowlist = TRADE_SCOPE_ALLOWLISTS[tradeKey];
  return allowlist?.length ? allowlist : null;
}

module.exports = {
  PLAN_EXPORT_TRADE_KEYS,
  TRADE_SCOPE_ALLOWLISTS,
  getTradeScopeAllowlist,
};
